name: Actualizar Feed y Generar Imagenes

on:
  workflow_dispatch:
  schedule:
    # HORARIOS PERÚ (UTC-5) AJUSTADOS A UTC
    - cron: '07 05 * * *' # 12:07 AM PE
    - cron: '07 08 * * *' # 03:07 AM PE
    - cron: '07 11 * * *' # 06:07 AM PE
    - cron: '07 14 * * *' # 09:07 AM PE
    - cron: '07 17 * * *' # 12:07 PM PE
    - cron: '07 20 * * *' # 03:07 PM PE
    - cron: '07 23 * * *' # 06:07 PM PE
    - cron: '07 02 * * *' # 09:07 PM PE

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360 # 6 Horas max (Seguridad)
    permissions:
      contents: write
    
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Ejecutar Script por Lotes
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: |
          # 1. Configurar Git antes de empezar
          git config --global user.name 'GitHub Action Bot'
          git config --global user.email 'action@github.com'
          
          # 2. Asegurar tener lo ultimo
          git pull origin main || true
          
          # 3. Correr Python
          python main.py
